net stop "ColdFusion MX Application Server"
net stop "ColdFusion MX 7 Application Server"
net stop "ColdFusion 8 Application Server"
net stop "ColdFusion 9 Application Server"
net stop "ColdFusion 10 Application Server"

net start "ColdFusion MX Application Server"
net start "ColdFusion MX 7 Application Server"
net start "ColdFusion 8 Application Server"
net start "ColdFusion 9 Application Server"
net start "ColdFusion 10 Application Server"
